### ISSUE TITLE
H1 - HIGH - BUG - Email tasks are not created when task group include filter (2nd Task in 3 step workflow)

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#625]
### Form Name: First / Second / Third (Task Groups: First Stage & Second Stage)
                            First2 / Second2 / Third2 (Task Groups: First Step wo filter & Second Step wo filter)

### Steps to reproduce the problem: In the first scenario starting with First fill out the form and check for tasks generation. Repeat with the second scenario starting with First2 fill out the form and check for tasks generation. You should see the first scenario do not create Second Stage tasks

Also after receiving Email if you see content but not start the task, an Error status is shown. It becomes later as completed when completed. That message could be confusing 
![image](https://user-images.githubusercontent.com/29519901/84969596-a4109580-b0de-11ea-875b-df433b77884c.png)
![image](https://user-images.githubusercontent.com/29519901/84969548-8cd1a800-b0de-11ea-924d-412810391373.png)
![image](https://user-images.githubusercontent.com/29519901/84969854-2305ce00-b0df-11ea-84ed-b680f94f0c06.png)

**Comment by nap2000** [comment]
In your task groups, "First Stage" and "Second Stage",  the assignment is to a user, ie not an email.  However the assignment value comes from the "email" question in the survey.  Also you don't seem to have selected "Assign from data values".  Is that correct?

**Comment by atl2017** [comment]
Hi Neil,

Sorry, apparently there is an error in the process design. I will close the issue and check again.

Thanks.

**Comment by atl2017** [comment]
> In your task groups, "First Stage" and "Second Stage", the assignment is to a user, ie not an email. However the assignment value comes from the "email" question in the survey. Also you don't seem to have selected "Assign from data values". Is that correct?

No Neil, I have found other issues that I am not sure if they are related with current:

1- Task Group before creation and after creation looks different. That´s why you saw a different design above:

BEFORE SAVING
![Captura2](https://user-images.githubusercontent.com/29519901/85186723-4310cb00-b260-11ea-9d52-4655d09f54dc.PNG)

AFTER SAVING AND EDITING:
![Captura3](https://user-images.githubusercontent.com/29519901/85186741-57ed5e80-b260-11ea-9ab8-a439736dad62.PNG)

In fact project name that it is shown at first does not relate with Existing Survey nor New Survey

2- Apparently advanced filter it is not working in Task Group = Second Step.

Task Groups =  Step 1 OK   Form1 -> Form2   by email
                         Step 2 Not OK   Form2  -> Form3  by email
                         Step 3 Not sure because depends on Step 2   Form3 -> Form4 by email

**Comment by nap2000** [comment]
OK.  I have fixed but not released, the issue whereby if you use a question to set the email address then the assignment type is not shown as "email" when editing.   However It is still correctly recorded as an email assignment type so this is not the issue you are reporting.  I will continue to look at it.

**Comment by atl2017** [comment]
Tested OK. Thank you very much!
Listed project is still wrong. Now email is OK
![image](https://user-images.githubusercontent.com/29519901/85285443-9187ba80-b456-11ea-843a-fb5b250b01aa.png)
